version: '3.7'

services:
  web:
    build: .
    #command: gunicorn dna_pilot_project.wsgi -b 0.0.0.0:8000
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=$SECRET_KEY
      - DATABASE_URL=$DATABASE_URL
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
