# Generated by Django 3.0.1 on 2020-04-15 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsid', models.CharField(max_length=20, unique=True)),
                ('chromosome', models.CharField(max_length=2)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genotype', models.CharField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variants.Variant')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variants.Variant')),
            ],
        ),
        migrations.AddIndex(
            model_name='uservariant',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
