# Generated by Django 3.0.5 on 2020-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication", name="rsid", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="publication", name="title", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="publication", name="trait", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recommendation", name="rsid", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recommendation", name="text", field=models.TextField(),
        ),
    ]
