# Generated by Django 3.0.5 on 2020-05-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_auto_20200430_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservariant',
            options={'permissions': [('premium_status', 'Access to premium features')]},
        ),
    ]
